apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-2
  namespace: magento-local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  storageClassName: local-storage 