---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-claim
  namespace: magento-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi