--- 
apiVersion: v1
kind: Service
metadata: 
  name: magentodemoapp-service
  namespace: magento-demo
spec: 
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  selector: 
    app: magento-demo-app