apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: magento-redis-dpy
  namespace: magento-demo
spec:
  selector:
    matchLabels:
      app: magento-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: magento-redis
    spec:
      containers:
      - name: master
        image: redis # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379