apiVersion: v1
kind: Service
metadata:
  name: magento-redis-service
  namespace: magento-demo
  labels:
    app: magento-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: magento-redis